basePath: /
host: localhost:8080
info:
  contact: {}
  description: This is a sample server for a book API.
  title: Book API
  version: "1.0"
paths: {}
schemes:
- http
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
